<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="18378" started-at="2018-07-26T18:32:00Z" finished-at="2018-07-26T18:32:19Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="18378" started-at="2018-07-26T18:32:00Z" finished-at="2018-07-26T18:32:19Z">
      <class name="script.TestScript">
        <test-method status="PASS" signature="preCondition()[pri:0, instance:script.TestScript@86be70a]" name="preCondition" is-config="true" duration-ms="6453" started-at="2018-07-26T18:32:00Z" finished-at="2018-07-26T18:32:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- preCondition -->
        <test-method status="FAIL" signature="invalidLogin()[pri:0, instance:script.TestScript@86be70a]" name="invalidLogin" duration-ms="3238" started-at="2018-07-26T18:32:07Z" finished-at="2018-07-26T18:32:10Z">
          <exception class="java.lang.AssertionError">
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.fail(Assert.java:95)
at script.TestScript.invalidLogin(TestScript.java:38)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invalidLogin -->
        <test-method status="PASS" signature="preCondition()[pri:0, instance:script.TestScript@86be70a]" name="preCondition" is-config="true" duration-ms="5420" started-at="2018-07-26T18:32:11Z" finished-at="2018-07-26T18:32:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- preCondition -->
        <test-method status="PASS" signature="validLogin()[pri:0, instance:script.TestScript@86be70a]" name="validLogin" duration-ms="2523" started-at="2018-07-26T18:32:16Z" finished-at="2018-07-26T18:32:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validLogin -->
      </class> <!-- script.TestScript -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
